import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faMapMarkerAlt, faCheckCircle, faBaby, faClock } from '@fortawesome/free-solid-svg-icons';
import { KIND_LABELS, MIN_AGE_TYPE_LABELS, OPENING_TYPE_LABELS } from '../constants/labels';
import { postSearch } from '../lib/nursery';
import Layout from '../components/layout';
import SearchForm from '../components/searchForm';

export default function Home({initialNurseries}) {
  const [nurseries, setNurseries] = useState(initialNurseries);
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="content m-4">
        <SearchForm setNurseries={setNurseries} />
      </div>

      <div className="content m-4">
        {nurseries.map((nursery) => (
          <div key={nursery.code}>
            <div className="block">
              <Link href={`/nurseries/${nursery.code}`}>
                <a style={{color:'#4a4a4a'}}>
                  <div className="is-pulled-left">
                    <p>
                      <span className="tag is-primary mr-2">{KIND_LABELS[nursery.kind]}</span>
                      <span className="has-text-weight-bold">{nursery.name}</span>
                    </p>
                    <p>
                      <span className="icon-text">
                        <span className="icon">
                          <FontAwesomeIcon icon={faMapMarkerAlt} size="lg" />
                        </span>
                        <span>{nursery.address}</span>
                      </span>
                    </p>
                    <p>
                      <span className="icon-text">
                        <span className="icon"><FontAwesomeIcon icon={faCheckCircle} size="lg" /></span>
                        <span>入園可能年齢：{MIN_AGE_TYPE_LABELS[nursery.minAgeType]} 〜</span>
                      </span>
                    </p>
                    <p className="is-hidden-mobile">
                      <span className="icon-text">
                        <span className="icon"><FontAwesomeIcon icon={faClock} size="lg" /></span>
                        <span>開所時間：{OPENING_TYPE_LABELS[nursery.openingType]}</span>
                      </span>
                    </p>
                    <p>
                      <span className="icon-text">
                        <span className="icon"><FontAwesomeIcon icon={faBaby} size="lg" /></span>
                        <span>定員：{nursery.capacity}人</span>
                      </span>
                    </p>
                  </div>
                  <div className="is-pulled-right">

                  </div>
                  <div className="is-clearfix"></div>
                </a>
              </Link>
            </div>
            <hr />
          </div>
        ))}
      </div>
    </Layout>
  )
}

export async function getStaticProps() {
  const res = await postSearch();
  const data = await res.json();
  if (res.status != 200) {
    throw Error(data.error);
  }

  return {
    props: {
      initialNurseries: data,
    }
  };
}
