import Head from 'next/head';
import { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faMapMarkerAlt } from '@fortawesome/free-solid-svg-icons'
import { KIND_LABELS, MIN_AGE_TYPE_LABELS, OPENING_TYPE_LABELS } from '../constants/labels';
import Layout from '../components/layout';
import SearchForm from '../components/searchForm';

export default function Home({initialNurseries}) {
  const [nurseries, setNurseries] = useState(initialNurseries);
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="section">
        <SearchForm setNurseries={setNurseries} />
      </div>

      {nurseries.map((nursery) => (
        <div className="box" key={nursery.code}>
          <p>
            <span className="tag is-primary mr-2">{KIND_LABELS[nursery.kind]}</span>
            <span className="has-text-weight-bold">{nursery.name}</span>
          </p>
          <p className="is-size-7">
            <span className="icon-text">
              <span className="icon">
                <FontAwesomeIcon icon={faMapMarkerAlt} size="lg" />
              </span>
              <span>{nursery.address}</span>
            </span>
          </p>
          <ul className="is-size-7">
            <li>入園可能年齢：{MIN_AGE_TYPE_LABELS[nursery.min_acceptable_age_type]} 〜</li>
            <li>保育時間：{OPENING_TYPE_LABELS[nursery.opening_type]}</li>
            <li>定員：TODO</li>
          </ul>
        </div>
      ))}
    </Layout>
  )
}

export async function getStaticProps() {
  const url = `${process.env.BASE_API_URL}/nurseries/search.json`;
  const data = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
    },
  }).then(res => res.json());
  return {
    props: {
      initialNurseries: data
    }
  };
}
